# Generated by Django 5.1.1 on 2024-09-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_alter_moodentry_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='KambingEntry',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='kambingentry',
            old_name='feelings',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='kambingentry',
            old_name='mood',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='kambingentry',
            old_name='mood_intensity',
            new_name='price',
        ),
    ]
