# Generated by Django 5.1.1 on 2024-09-24 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_moodentry_kambingentry_delete_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('is_happy', models.BooleanField()),
                ('muncul', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='kambingentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
